name: 'Lint monorepo'
description: 'Lint monorepo using sui-lint'

runs:
  using: composite

  steps:
      - name: Install
        uses: scmspain/platform-common--actions/frontend/install@v0

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Lint
        shell: bash
        run: make lint
        env:
          LINT_JS_FLAGS: '--force-full-lint --reporter .scripts/sui-lint-js-reporter.bundle.js'
          LINT_REPOSITORY_FLAGS: '--reporter .scripts/sui-lint-repository-reporter.bundle.js'
        
