name: 'Lint monorepo'
description: 'Lint monorepo using sui-lint'

inputs:
  lint-js-flags:
    description: "Flags to be apply to sui-lint js when is executed"
    required: false

  lint-repository-flags:
    description: "Flags to be apply to sui-lint repository when is executed"
    required: false

runs:
  using: composite

  steps:
      - name: Install
        uses: scmspain/platform-common--actions/frontend/install@v0

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Lint
        shell: bash
        run: make lint
          # env:
          #   LINT_JS_FLAGS: ${{ inputs.lint-js-flags }}
          #   LINT_REPOSITORY_FLAGS: ${{ inputs.lint-repository-flags }}
