
name: 'Test UI components'
description: 'Test only the UI components'

inputs:
  stage:
    description: "Stage used inside of the image"
    required: true

  pattern:
    description: "Which components you want to test"
    required: true

  command:
    description: "Which command run inside of the docker"
    required: false
    default: "make test"

runs:
  using: composite

  steps:
    - name: Restore App
      uses: actions/cache/restore@v3
      with:
        fail-on-cache-miss: true
        key: ${{ runner.OS }}-${{ github.sha }}-${{ inputs.stage }}-monorepo-build
        path: './'

    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Execute tests
      shell: bash
      run: docker-compose -f .docker/compose.test.yaml up --exit-code-from runner
      env:
        STAGE: ${{ inputs.stage }}
        PATTERN: '${{ inputs.pattern }}'
        COMMAND: ${{ inputs.command }}
