name: 'Lint and test monorepo'
description: 'Testing not include the E2E tests'

inputs:
  stage:
    description: "Stage used inside of the image"
    required: true

runs:
  using: composite

  steps:
    - name: Install
      uses: scmspain/platform-common--actions/frontend/install@v0
      with:
        build: 'true'

    - name: Lint
      shell: bash
      run: npm run lint

    - name: Setup Chrome
      id: setup-chrome
      uses: scmspain/platform-common--actions/frontend/setup-chrome@v0

    - name: Test
      shell: bash
      run: npm run test
      env:
        CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}
        NODE_ENV: production
        STAGE: ${{ inputs.stage }}
        TEST_FLAG_CLIENT: --headless
