name: 'Lint and test monorepo'
description: 'Testing not include the E2E tests'

runs:
  using: composite

  steps:
    - name: Install
      uses: scmspain/platform-common--actions/frontend/install@v0
      with:
        build: 'true'

    - name: Lint
      shell: bash
      run: npm run lint

    - name: Test
      shell: bash
      run: npm run test
