name: 'Upload the public folder to our S3 folder'
description: 'Upload folder and setup cache policies'

inputs:
  aws-account-id:
    description: "AWS account identifier"
    required: false
    default: ""

  aws-region:
    description: "AWS region"
    required: false
    default: "eu-west-3"

  s3-bucket:
    description: "S3 Bucket where we want to upload our assets"
    required: true

  stage:
    description: "The place where static assets are located"
    required: true

runs:
  using: composite
  steps:
      - name: Restore App
        uses: actions/cache/restore@v3
        with:
          fail-on-cache-miss: true
          key: ${{ runner.OS }}-${{ github.sha }}-${{inputs.stage}}-monorepo-build
          path: './'

      - name: Tap
        shell: bash
        run: ls -pal ./

      - name: Authenticate with AWS account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/github-actions-deployments
          aws-region: ${{ inputs.aws-region }}
          role-duration-seconds: 1200

      - name: Deploy to S3
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: sync
          source: ./app/public
          destination: ${{ inputs.s3-bucket }}
          # s3://scm-milanuncios-frontend-pre/pet/${{ inputs.stage }}/
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
          aws_session_token: $AWS_SESSION_TOKEN
          aws_region: ${{ inputs.aws-region }}
          flags: "--cache-control public,max-age=31536000,immutable --exclude manifest.json --exclude asset-manifest.json --exclude service-worker.js --exclude index.html --exclude 500.html --exclude 404.html"
