name: 'Test monorepo'
description: 'Testing not include the E2E tests'

inputs:
  stage:
    description: "Stage used inside of the image"
    required: true

  command:
    description: "Which command run inside of the docker"
    required: false
    default: "make test"

runs:
  using: composite

  steps:
      - name: Install
        uses: scmspain/platform-common--actions/frontend/install@v0

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Execute tests
        shell: bash
        run: docker-compose -f .docker/compose.test.yaml up --exit-code-from runner
        env:
          STAGE: ${{ inputs.stage }}
          TEST_FLAG: --headless
          COMMAND: ${{ inputs.command }}

