name: 'Dockerize'
description: 'Create and upload a Docker image to our hub'

inputs:
  stage:
    description: "Stage used inside of the image"
    required: true

  suffix:
    description: "Docker Image suffix"
    required: true

runs:
  using: composite
  steps:
    - name: Restore App
      uses: actions/cache/restore@v3
      with:
        fail-on-cache-miss: true
        key: ${{ runner.OS }}-${{ github.sha }}-${{ inputs.stage }}-app
        path: './app'

    - name: Tap
      shell: bash
      run: ls -pal ./app

    - name: Build docker image
      uses: common-platform/actions/build-image@v0
      with:
        dockerfile-path: ./app/Dockerfile
        push-image: true
        additional-tags: '["${{ github.sha }}"]'
        build-args: '{"STAGE": "${{ inputs.stage }}", "CDN": "https://scm-milanuncios-frontend-pre.milanuncios.net/pet/${{ inputs.stage }}/"}'
        suffix: '${{ inputs.suffix }}'
        #'${{ inputs.app }}-${{ inputs.stage }}'
