name: 'Test UI components'
description: 'Test only the UI components'

inputs:
  pattern:
    description: "Which components you want to test"
    required: true

runs:
  using: composite

  steps:
    - name: Restore App
      uses: actions/cache/restore@v3
      with:
        fail-on-cache-miss: true
        key: ${{ runner.OS }}-${{ github.sha }}-${{ inputs.stage }}-monorepo-build
        path: './'

    - name: Tap
      shell: bash
      run: |
        cd ./packages/ui
        make test
      env:
        PATTERN: '${{ inputs.pattern }}'
