# https://github.com/docker/awesome-compose
services:
  runner:
    build:
      dockerfile: "${PWD}/.docker/Dockerfile.test"
      context: "${PWD}"
      args:
        CONSOLE: true
        STAGE: ${STAGE:-production}
        NODE_ENV: ${NODE_ENV:-production}
        PATTERN: ${PATTERN}
    cap_add:
      - CAP_SYS_ADMIN
    volumes:
      - ${PWD}/node_modules:/usr/src/mono/node_modules
    command: ${COMMAND:-"make test"}
