# https://github.com/docker/awesome-compose
services:
  frontend:
    build:
      dockerfile: "${PWD}/.docker/Dockerfile"
      context: "${PWD}"
      args:
        CONSOLE: true
        STAGE: production
        NODE_ENV: production
        CDN: ${CDN:-/}
    environment:
      PORT: 2023
    ports:
      - 2023:2023
