ARG BASE_IMG

FROM ${BASE_IMG} as base

FROM amazon/aws-cli

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY

ENV AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY

WORKDIR /usr/src/app

COPY --from=base /usr/src/app .
COPY .docker/scripts/aws_upload.sh .

ENTRYPOINT ./aws_upload.sh
