name: 'Execute E2E tests for diferents scopes'
description: 'Use our docker image of the app to tests our code'

inputs:
  scope:
    description: "The place where static assets are located"
    required: true

  stage:
    description: "Stage used inside of the image"
    required: true

  docker-image:
    description: "Docker IMG to be used as Application"
    required: true

runs:
  using: composite

  steps:
    - name: Test
      shell: bash
      run: docker-compose -f .docker/compose.e2e.yaml up --exit-code-from e2e
      env:
        APP_IMG: ${{ inputs.docker-image }}
        E2E_FLAGS: --scope=${{ inputs.scope }}
